name: ${LVN_APP_NAME}
include:
  - path: base_spec.yml
    relativePaths: false
  - path: ${LVN_IOS_INCLUDE_PATH}
    relativePaths: false
  - path: ${LVN_MACOS_INCLUDE_PATH}
    relativePaths: false
  - path: ${LVN_WATCHOS_INCLUDE_PATH}
    relativePaths: false
